import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <div className={styles.navContainer}>
          <div className={styles.logContainer}>
            <img src="/logo.svg" alt="logo" />
            <span>StartupLanding</span>
          </div>
          <nav>
            <ul>
              <li>
                <Link href="/news/details">Pricing</Link>
              </li>
              <li>Support</li>
              <li>Register</li>
              <li>Get Started</li>
            </ul>
          </nav>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </div>
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h1 className={styles.title}>
              A Creative way to
              <br /> grow your Exciting
              <br /> Business model
            </h1>
            <p className={styles.description}>
              Get your blood tests delivered at let home collect sample from the
              victory of the managments that supplies best design system
              guidelines ever.
            </p>
            <div className={styles.inputMargins}>
              <input
                className={styles.inputBox}
                type="text"
                placeholder="Enter Email address"
              />{" "}
              <button className={styles.buttonInput}>Subscribe</button>
            </div>
            <div className={styles.sponsordSection}>
              <span>Sponsored by:</span>
              <a>
                <img src="./paypal.svg" alt="paypals" />
              </a>
              <a>
                <img src="./google.svg" alt="google" />
              </a>
              <a>
                <img src="./dropBox_vector.svg" alt="vector" />
                <img src="./dropBoxText_vector.svg" alt="dropbox" />
              </a>
            </div>
          </div>
          <div className={styles.card}>
            <img src="./progress_1.svg" alt="progress" />
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.cardSecSection}>
            <h2>Go Beyond unlimited features</h2>
            <p>
              Focus only on the meaning, we take care of the design. As soon as
              the meeting end you can export in one click into your preferred
              format.
            </p>
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.cardSec}>
            <a>
              <img src="./home_icons.svg" alt="Market Place" />
            </a>
            <div className={styles.random}>
              <h2>Trusted marketplace</h2>
              <p>
                Our homes are designed to be move-in ready. Think furnished
                common areas, super fast wifi, and flexible leases.
              </p>
            </div>
          </div>
          <div className={styles.cardSec}>
            <a>
              <img src="./gift_box.svg" alt="Market Place" />
            </a>
            <div className={styles.random}>
              <h2>Customer Gift vouchers</h2>
              <p>
                Our homes are designed to be move-in ready. Think furnished
                common areas, super fast wifi, and flexible leases.
              </p>
            </div>
          </div>
          <div className={styles.cardSec}>
            <a>
              <img src="./cup_vector.svg" alt="Market Place" />
            </a>
            <div className={styles.random}>
              <h2>Multiple Awards wins</h2>
              <p>
                Our homes are designed to be move-in ready. Think furnished
                common areas, super fast wifi, and flexible leases.
              </p>
            </div>
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.card}>
            <img src="./result_vector.svg" alt="progress" />
          </div>
          <div className={styles.card}>
            <h2>
              We help you to boost your
              <br /> business profitable with
              <br /> our talent marketer
            </h2>
            <p className={styles.description}>
              Get your tests delivered at let home collect sample from the
              victory of the managments that supplies best design system
              guidelines ever.
            </p>
            <div className={styles.inputMargins}>
              <img src="./combined_shape.svg" />
              <span>Unlimited design possibility</span>
            </div>
            <div className={styles.inputMargins}>
              <img src="./combined_shape.svg" />
              <span>Completley responsive features</span>
            </div>
            <h4>Explore Details &rarr;</h4>
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2 className={styles.title}>
              we are committed to using
              <br /> fact-based knowledge to
              <br /> our customers
            </h2>
            <p className={styles.description}>
              Get your tests delivered at let home collect sample from the
              victory of the managments that supplies best design system
              guidelines ever. Get your tests delivered at let home collect
              sample.
            </p>
            <h4>Explore Details &rarr;</h4>
          </div>
          <div className={styles.card}>
            <img src="./profile_vector.svg" alt="progress" />
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.cardSecSection}>
            <h2>
              More than thousand of user we have worldwide with happy feedback
            </h2>
            <p>
              Focus only on the meaning, we take care of the design. As soon as
              the meeting end you can export in one click into your preferred.
            </p>
          </div>
          <div>
            <a>
              <img src="./users_vector.svg" alt="users" />
            </a>
          </div>
        </div>
        <div className={styles.gridContainer}>
          <div className={styles.grid}>
            <div className={styles.cardSecSection}>
              <h2>Let’s meet how its work</h2>
              <p>
                Focus only on the meaning, we take care of the design. As soon
                as the meeting end you can export in one click into your
                preferred format.
              </p>
            </div>
          </div>
          <div className={styles.grid}>
            <div className={styles.cardSec}>
              <span>01</span>
              <div className={styles.random}>
                <h2>Trusted marketplace</h2>
                <p>
                  Our homes are designed to be move-in ready. Think furnished
                  common areas, super fast wifi, and flexible leases.
                </p>
              </div>
            </div>
            <div className={styles.cardSec}>
              <span>02</span>
              <div className={styles.random}>
                <h2>Customer Gift vouchers</h2>
                <p>
                  Our homes are designed to be move-in ready. Think furnished
                  common areas, super fast wifi, and flexible leases.
                </p>
              </div>
            </div>
            <div className={styles.cardSec}>
              <span>03</span>
              <div className={styles.random}>
                <h2>Multiple Awards wins</h2>
                <p>
                  Our homes are designed to be move-in ready. Think furnished
                  common areas, super fast wifi, and flexible leases.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.cardSecSection}>
            <h2>
              Meet our support team who always work hardly behind the scenes
            </h2>
            <p>
              Meet our support team who always work hardly behind the scenes
            </p>
          </div>
          <img src="./members_pics.svg" alt="Memberts" />
          <div className={styles.ContactUsCard}>
            <span>Do you have any question? Feel free to contact us</span>
            <img src="./arrow_vector.svg" alt="arrow" />
            <div className={styles.verticalBars}>
              <a>
                <img src="./verticals_vectors_up.svg" alt="ups" />
              </a>
              <button>contact us now</button>
              <a>
                <img src="./verticals_vectors_down.svg" alt="ups" />
              </a>
            </div>
          </div>
        </div>
        <div className={styles.gridFooter}>
          <div>
            <div className={styles.logContainer}>
              <img src="/logo.svg" alt="logo" />
              <span>StartupLanding</span>
            </div>
            <p>Terms of use | Privacy</p>
            <p>Copyright by 2019 Redq, Inc.</p>
          </div>
          <div>
            <div className={styles.logContainer}>
              <span>About Us</span>
            </div>
            <ul>
              <li>Support Center</li>
              <li>Customer Support</li>
              <li>About Us</li>
              <li>Copyright</li>
            </ul>
          </div>
          <div>
            <div className={styles.logContainer}>
              <span>Our Information</span>
            </div>
            <ul>
              <li>Support Center</li>
              <li>Customer Support</li>
              <li>About Us</li>
              <li>Copyright</li>
            </ul>
          </div>
          <div>
            <div className={styles.logContainer}>
              <span>My Account</span>
            </div>
            <ul>
              <li>Support Center</li>
              <li>Customer Support</li>
              <li>About Us</li>
              <li>Copyright</li>
            </ul>
          </div>
          <div>
            <div className={styles.logContainer}>
              <span>Connect</span>
            </div>
            <div className={styles.SocialIcons}>
              <div>
                <img src="./facebook_vector.svg" alt="FaceBook" />
                <span>FaceBook</span>
              </div>
              <div>
                <img src="./twitter_vector.svg" alt="Twitter" />
                <span>Twitter</span>
              </div>
              <div>
                <img src="./github_vector.svg" alt="GitHub" />
                <span>GitHub</span>
              </div>
              <div>
                <img src="./dribble_vector.svg" alt="Dribble" />
                <span>Dribble</span>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
