import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import showProgressImage from "../public/progress_1.svg";
import brandLogo from "../public/logo.svg";
import payPalImage from "../public/paypal.svg";
import googleImage from "../public/google.svg";
import dropBox_vector from "../public/dropBox_vector.svg";
import dropBoxText_vector from "../public/dropBoxText_vector.svg";
import homeIcon from "../public/home_icons.svg";
import giftIcon from "../public/gift_box.svg";
import cupIcon from "../public/cup_vector.svg";
import resultVector from "../public/result_vector.svg";
import circleVector from "../public/combined_shape.svg";
import profileVector from "../public/profile_vector.svg";
import usersVector from "../public/users_vector.svg";
import membersPic from "../public/members_pics.svg";
import arrowVector from "../public/arrow_vector.svg";
import verticalsArrowVectorUp from "../public/verticals_vectors_up.svg";
import verticalsArrowVectorDown from "../public/verticals_vectors_down.svg";
import faceBookIcon from "../public/facebook_vector.svg";
import twitterIcon from "../public/twitter_vector.svg";
import gitHubIcon from "../public/github_vector.svg";
import dribbleIcon from "../public/dribble_vector.svg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navContainer}>
        <div className={styles.logContainer}>
          <Image src={brandLogo} alt="logo" />
          <span>StartupLanding</span>
        </div>
        <nav>
          <ul>
            <li>
              <Link href="/news/details">Pricing</Link>
            </li>
            <li>Support</li>
            <li>Register</li>
            <li>Get Started</li>
          </ul>
        </nav>
      </div>
      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h1 className={styles.title}>
              A Creative way to
              <br /> grow your Exciting
              <br /> Business model
            </h1>
            <p className={styles.description}>
              Get your blood tests delivered at let home collect sample from the
              victory of the managments that supplies best design system
              guidelines ever.
            </p>
            <div className={styles.inputMargins}>
              <input
                className={styles.inputBox}
                type="text"
                placeholder="Enter Email address"
              />{" "}
              <button className={styles.buttonInput}>Subscribe</button>
            </div>
            <div className={styles.sponsordSection}>
              <span>Sponsored by:</span>
              <a>
                <Image src={payPalImage} alt="paypals" />
              </a>
              <a>
                <Image src={googleImage} alt="google" />
              </a>
              <a>
                <Image src={dropBox_vector} alt="vector" />
                <Image src={dropBoxText_vector} alt="dropbox" />
              </a>
            </div>
          </div>
          <div className={styles.card}>
            <Image src={showProgressImage} alt="progress" />
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.cardSecSection}>
            <h2>Go Beyond unlimited features</h2>
            <p>
              Focus only on the meaning, we take care of the design. As soon as
              the meeting end you can export in one click into your preferred
              format.
            </p>
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.cardSec}>
            <a>
              <Image
                src={homeIcon}
                alt="Market Place"
                width={170}
                height={170}
              />
            </a>
            <div className={styles.random}>
              <h2>Trusted marketplace</h2>
              <p>
                Our homes are designed to be move-in ready. Think furnished
                common areas, super fast wifi, and flexible leases.
              </p>
            </div>
          </div>
          <div className={styles.cardSec}>
            <a>
              <Image
                src={giftIcon}
                alt="Market Place"
                width={170}
                height={170}
              />
            </a>
            <div className={styles.random}>
              <h2>Customer Gift vouchers</h2>
              <p>
                Our homes are designed to be move-in ready. Think furnished
                common areas, super fast wifi, and flexible leases.
              </p>
            </div>
          </div>
          <div className={styles.cardSec}>
            <a>
              <Image
                src={cupIcon}
                alt="Market Place"
                width={170}
                height={170}
              />
            </a>
            <div className={styles.random}>
              <h2>Multiple Awards wins</h2>
              <p>
                Our homes are designed to be move-in ready. Think furnished
                common areas, super fast wifi, and flexible leases.
              </p>
            </div>
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.card}>
            <Image src={resultVector} alt="progress" />
          </div>
          <div className={styles.card}>
            <h2>
              We help you to boost your
              <br /> business profitable with
              <br /> our talent marketer
            </h2>
            <p className={styles.description}>
              Get your tests delivered at let home collect sample from the
              victory of the managments that supplies best design system
              guidelines ever.
            </p>
            <div className={styles.inputMargins}>
              <Image src={circleVector} />
              <span>Unlimited design possibility</span>
            </div>
            <div className={styles.inputMargins}>
              <Image src={circleVector} />
              <span>Completley responsive features</span>
            </div>
            <h4>Explore Details &rarr;</h4>
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2 className={styles.title}>
              we are committed to using
              <br /> fact-based knowledge to
              <br /> our customers
            </h2>
            <p className={styles.description}>
              Get your tests delivered at let home collect sample from the
              victory of the managments that supplies best design system
              guidelines ever. Get your tests delivered at let home collect
              sample.
            </p>
            <h4>Explore Details &rarr;</h4>
          </div>
          <div className={styles.card}>
            <Image src={profileVector} alt="progress" />
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.cardSecSection}>
            <h2>
              More than thousand of user we have worldwide with happy feedback
            </h2>
            <p>
              Focus only on the meaning, we take care of the design. As soon as
              the meeting end you can export in one click into your preferred.
            </p>
          </div>
          <div>
            <a>
              <Image src={usersVector} alt="users" />
            </a>
          </div>
        </div>
        <div className={styles.gridContainer}>
          <div className={styles.grid}>
            <div className={styles.cardSecSection}>
              <h2>Let’s meet how its work</h2>
              <p>
                Focus only on the meaning, we take care of the design. As soon
                as the meeting end you can export in one click into your
                preferred format.
              </p>
            </div>
          </div>
          <div className={styles.grid}>
            <div className={styles.cardSec}>
              <span>01</span>
              <div className={styles.random}>
                <h2>Trusted marketplace</h2>
                <p>
                  Our homes are designed to be move-in ready. Think furnished
                  common areas, super fast wifi, and flexible leases.
                </p>
              </div>
            </div>
            <div className={styles.cardSec}>
              <span>02</span>
              <div className={styles.random}>
                <h2>Customer Gift vouchers</h2>
                <p>
                  Our homes are designed to be move-in ready. Think furnished
                  common areas, super fast wifi, and flexible leases.
                </p>
              </div>
            </div>
            <div className={styles.cardSec}>
              <span>03</span>
              <div className={styles.random}>
                <h2>Multiple Awards wins</h2>
                <p>
                  Our homes are designed to be move-in ready. Think furnished
                  common areas, super fast wifi, and flexible leases.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.cardSecSection}>
            <h2>
              Meet our support team who always work hardly behind the scenes
            </h2>
            <p>
              Meet our support team who always work hardly behind the scenes
            </p>
          </div>
          <Image src={membersPic} alt="Memberts" />
          <div className={styles.ContactUsCard}>
            <span>Do you have any question? Feel free to contact us</span>
            <Image src={arrowVector} alt="arrow" width={300} height={300} />
            <div className={styles.verticalBars}>
              <a>
                <Image src={verticalsArrowVectorUp} alt="ups" />
              </a>
              <button>contact us now</button>
              <a>
                <Image src={verticalsArrowVectorDown} alt="ups" />
              </a>
            </div>
          </div>
        </div>
        <div className={styles.gridFooter}>
          <div>
            <div className={styles.logContainer}>
              <Image src={brandLogo} alt="logo" />
              <span>StartupLanding</span>
            </div>
            <p>Terms of use | Privacy</p>
            <p>Copyright by 2019 Redq, Inc.</p>
          </div>
          <div>
            <div className={styles.logContainer}>
              <span>About Us</span>
            </div>
            <ul>
              <li>Support Center</li>
              <li>Customer Support</li>
              <li>About Us</li>
              <li>Copyright</li>
            </ul>
          </div>
          <div>
            <div className={styles.logContainer}>
              <span>Our Information</span>
            </div>
            <ul>
              <li>Support Center</li>
              <li>Customer Support</li>
              <li>About Us</li>
              <li>Copyright</li>
            </ul>
          </div>
          <div>
            <div className={styles.logContainer}>
              <span>My Account</span>
            </div>
            <ul>
              <li>Support Center</li>
              <li>Customer Support</li>
              <li>About Us</li>
              <li>Copyright</li>
            </ul>
          </div>
          <div>
            <div className={styles.logContainer}>
              <span>Connect</span>
            </div>
            <div className={styles.SocialIcons}>
              <div>
                <Image src={faceBookIcon} alt="FaceBook" />
                <span>FaceBook</span>
              </div>
              <div>
                <Image src={twitterIcon} alt="Twitter" />
                <span>Twitter</span>
              </div>
              <div>
                <Image src={gitHubIcon} alt="GitHub" />
                <span>GitHub</span>
              </div>
              <div>
                <Image src={dribbleIcon} alt="Dribble" />
                <span>Dribble</span>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
